Repository F2I-Consulting/fesapi, pull requests merged in 2019-04, with the labels that each got.

#127 Bug fix : RepresentatonSetRepresentation has no interpretation
  example/example.cpp
  src/resqml2/RepresentationSetRepresentation.cpp
  src/resqml2/RepresentationSetRepresentation.h
  src/resqml2_0_1/StratigraphicColumn.cpp
Labels: bug

#128 Update WITSML 2.0 Well swig support
  cmake/FesapiJavaExample.java
  cmake/Program.cs
  example/example.cpp
  swig/swigWitsml2_0Include.i
Labels: enhancement

#132 Fix VERY minor "misleading indentation" warnings from GCC 7.3
  src/common/HdfProxy.cpp
  src/resqml2_0_1/IjkGridLatticeRepresentation.cpp
  src/resqml2_0_1/PolylineRepresentation.cpp
Labels: bug, enhancement

#137 Fix compiler error with VS2017 with /std:c++17
  src/tools/GuidTools.cpp
Labels: enhancement

#136 Add string getters for Witsml 2.0 wellbore completion md uom
  example/example.cpp
  src/witsml2_0/WellboreCompletion.cpp
  src/witsml2_0/WellboreCompletion.h
  swig/swigWitsml2_0Include.i
Labels: enhancement

#135 Modified to build and work with either HDF5 1.8 or 1.10
  CMakeLists.txt
  README.md
  cmake/HidtType.h.in
  cmake/cmake.JPG
  cmake/cmake.PNG
  src/CMakeLists.txt
  src/common/AbstractHdfProxy.cpp
  src/common/AbstractHdfProxy.h
  src/common/HdfProxy.cpp
  src/common/HdfProxy.h
  src/resqml2_0_1/HdfProxy.cpp
  src/resqml2_0_1/HdfProxy.h
  src/resqml2_0_1/IjkGridExplicitRepresentation.cpp
  src/resqml2_0_1/IjkGridParametricRepresentation.cpp
  swig/swigModule.i
Labels: enhancement
