Repository F2I-Consulting/fesapi, pull requests merged in 2019-03, with the labels that each got.

#106 Support for reading RESQML 2.0 sealed surface framework
  CONTRIBUTING.md
  example/example.cpp
  src/CMakeLists.txt
  src/common/AbstractObject.cpp
  src/common/AbstractObject.h
  src/common/EpcDocument.cpp
  src/common/EpcDocument.h
  src/common/HdfProxy.cpp
  src/resqml2/AbstractRepresentation.cpp
  src/resqml2/AbstractRepresentation.h
  src/resqml2/Activity.h
  src/resqml2_0_1/AbstractSurfaceFrameworkRepresentation.cpp
  src/resqml2_0_1/AbstractSurfaceFrameworkRepresentation.h
  src/resqml2_0_1/AbstractSurfaceRepresentation.cpp
  src/resqml2_0_1/EarthModelInterpretation.cpp
  src/resqml2_0_1/EarthModelInterpretation.h
  src/resqml2_0_1/GeneticBoundaryFeature.cpp
  src/resqml2_0_1/GeneticBoundaryFeature.h
  src/resqml2_0_1/NonSealedSurfaceFrameworkRepresentation.cpp
  src/resqml2_0_1/NonSealedSurfaceFrameworkRepresentation.h
  src/resqml2_0_1/SealedSurfaceFrameworkRepresentation.cpp
  src/resqml2_0_1/SealedSurfaceFrameworkRepresentation.h
  src/resqml2_0_1/StratigraphicUnitFeature.cpp
  swig/swigModule.i
  swig/swigResqml2_0_1Include.i
Labels: enhancement

#108 Sealed volume framework
  example/example.cpp
  src/common/EpcDocument.cpp
  src/common/EpcDocument.h
  src/common/EpcExternalPartReference.cpp
  src/common/EpcExternalPartReference.h
  src/epc/ContentType.h
  src/epc/CoreProperty.h
  src/epc/FileContentType.h
  src/epc/FileCoreProperties.h
  src/epc/FilePart.h
  src/epc/FileRelationship.h
  src/epc/Package.h
  src/epc/Relationship.h
  src/resqml2/AbstractColumnLayerGridRepresentation.h
  src/resqml2/AbstractFeature.cpp
  src/resqml2/AbstractFeature.h
  src/resqml2/AbstractRepresentation.cpp
  src/resqml2/AbstractRepresentation.h
  src/resqml2/ActivityTemplate.cpp
  src/resqml2/ActivityTemplate.h
  src/resqml2/RepresentationSetRepresentation.cpp
  src/resqml2/RepresentationSetRepresentation.h
  src/resqml2/SubRepresentation.cpp
  src/resqml2/SubRepresentation.h
  src/resqml2/TimeSeries.cpp
  src/resqml2/TimeSeries.h
  src/resqml2_0_1/AbstractIjkGridRepresentation.cpp
  src/resqml2_0_1/AbstractIjkGridRepresentation.h
  src/resqml2_0_1/AbstractSurfaceFrameworkRepresentation.cpp
  src/resqml2_0_1/AbstractSurfaceFrameworkRepresentation.h
  src/resqml2_0_1/ActivityTemplate.cpp
  src/resqml2_0_1/ActivityTemplate.h
  src/resqml2_0_1/NonSealedSurfaceFrameworkRepresentation.cpp
  src/resqml2_0_1/NonSealedSurfaceFrameworkRepresentation.h
  src/resqml2_0_1/PlaneSetRepresentation.h
  src/resqml2_0_1/RepresentationSetRepresentation.h
  src/resqml2_0_1/SealedSurfaceFrameworkRepresentation.cpp
  src/resqml2_0_1/SealedSurfaceFrameworkRepresentation.h
  src/resqml2_0_1/SealedVolumeFrameworkRepresentation.cpp
  src/resqml2_0_1/SealedVolumeFrameworkRepresentation.h
  src/resqml2_0_1/StratigraphicUnitInterpretation.cpp
  src/resqml2_0_1/StratigraphicUnitInterpretation.h
  src/resqml2_0_1/StringTableLookup.cpp
  src/resqml2_0_1/StringTableLookup.h
  src/resqml2_0_1/SubRepresentation.h
  src/resqml2_0_1/WellboreFrameRepresentation.cpp
  src/resqml2_0_1/WellboreFrameRepresentation.h
  src/resqml2_0_1/WellboreMarker.cpp
  src/resqml2_0_1/WellboreMarker.h
  src/resqml2_0_1/WellboreMarkerFrameRepresentation.cpp
  src/resqml2_0_1/WellboreTrajectoryRepresentation.cpp
  src/resqml2_0_1/WellboreTrajectoryRepresentation.h
  src/witsml2_0/Well.cpp
  src/witsml2_0/Well.h
Labels: enhancement

#111 Fix unit tests
  doc/mainpage.md
  src/epc/Package.cpp
  src/resqml2_0_1/ActivityTemplate.cpp
  src/resqml2_0_1/WellboreMarker.cpp
  src/resqml2_0_1/WellboreMarker.h
  src/resqml2_0_1/WellboreMarkerFrameRepresentation.cpp
  src/resqml2_0_1/WellboreMarkerFrameRepresentation.h
  test/resqml2_0_1test/AbstractObjectTest.cpp
  test/resqml2_0_1test/AbstractRepresentationTest.cpp
  test/resqml2_0_1test/SeismicLineRepresentationTest.cpp
  test/resqml2_0_1test/WellboreMarkerFrameRepresentationTest.cpp
Labels: bug

#112 Automatically run unit tests
  .travis.yml
  CMakeLists.txt
  appveyor.yml
  cmake/Program.cs
  example/example.cpp
  src/epc/FileRelationship.cpp
  src/epc/Package.cpp
  src/resqml2/AbstractRepresentation.cpp
  src/resqml2_0_1/Grid2dRepresentation.cpp
  src/resqml2_0_1/IjkGridParametricRepresentation.cpp
  test/AbstractTest.cpp
  test/CMakeLists.txt
  test/resqml2_0_1test/AbstractBigIjkGridRepresentationTest.cpp
  test/resqml2_0_1test/AbstractRepresentationTest.cpp
  test/resqml2_0_1test/StratigraphicColumnRankInterpretationTest.cpp
  test/resqml2_0_1test/StratigraphicUnitInterpretationTest.cpp
Labels: enhancement

#118 Start to add getters and setters to WITSML2 Well
  CMakeLists.txt
  cmake/AssemblyInfo.cs
  cmake/FesapiJavaExample.java
  cmake/fesapiCs.csproj.template
  example/example.cpp
  src/CMakeLists.txt
  src/common/EpcDocument.cpp
  src/common/EpcDocument.h
  src/resqml2/AbstractProperty.cpp
  src/resqml2/AbstractProperty.h
  src/resqml2/PropertyKind.cpp
  src/resqml2/PropertyKind.h
  src/resqml2_0_1/CategoricalProperty.cpp
  src/resqml2_0_1/CommentProperty.cpp
  src/resqml2_0_1/ContinuousProperty.cpp
  src/resqml2_0_1/DiscreteProperty.cpp
  src/resqml2_0_1/PropertyKind.cpp
  src/resqml2_0_1/PropertyKind.h
  src/tools/TimeTools.cpp
  src/tools/TimeTools.h
  src/witsml2_0/Well.cpp
  src/witsml2_0/Well.h
Labels: bug, enhancement

#123 WITSML 2.0 perforation improvment, fix cs example
  cmake/Program.cs
  example/example.cpp
  src/witsml2_0/WellboreCompletion.cpp
  src/witsml2_0/WellboreCompletion.h
  swig/swigWitsml2_0Include.i
Labels: bug, enhancement
