Repository F2I-Consulting/fesapi, pull requests merged in 2020-08, with the labels that each got.

#237 Update swig support and add PropertyKind.getUomAsString()
  azure-pipelines.yml
  src/eml2/PropertyKind.h
  src/eml2_1/PropertyKind.cpp
  src/eml2_1/PropertyKind.h
  src/eml2_3/PropertyKind.cpp
  src/eml2_3/PropertyKind.h
  src/resqml2/StratigraphicColumnRankInterpretation.cpp
  src/resqml2/StratigraphicColumnRankInterpretation.h
  src/resqml2/StratigraphicOccurrenceInterpretation.h
  src/resqml2/WellboreMarkerFrameRepresentation.h
  src/resqml2_0_1/PropertyKind.cpp
  src/resqml2_0_1/PropertyKind.h
  src/resqml2_0_1/WellboreMarkerFrameRepresentation.cpp
  src/resqml2_0_1/WellboreMarkerFrameRepresentation.h
  src/resqml2_2/WellboreMarkerFrameRepresentation.cpp
  src/resqml2_2/WellboreMarkerFrameRepresentation.h
  swig/swigEml2Include.i
  swig/swigEml2_3Include.i
  swig/swigResqml2Include.i
  swig/swigWitsml2_0Include.i
Labels: build, enhancement

#238 Bug fix: error while reading unsplitted parametric IJK grids geometry
  example/example.cpp
  src/resqml2/IjkGridParametricRepresentation.cpp
Labels: bug

#239 Add SWIG support for WellboreMarker
  cmake/swigCsInclude.i
  cmake/swigJavaInclude.i
Labels: bug

#240 Perf : Do no more read EPC based on part name but now incrementally
  src/common/EpcDocument.cpp
  src/epc/Package.cpp
  src/resqml2/CulturalFeature.h
Labels: enhancement
