Repository F2I-Consulting/fesapi, pull requests merged in 2020-12, with the labels that each got.

#260 Python wrapping support
  .gitignore
  README.md
  azure-pipelines.yml
  cmake/HdfProxyFactoryExample.cs
  cmake/setup.py.in
  cmake/setup_etp.py.in
  cmake/swigPythonInclude.i.in
  docker/trusty/Dockerfile
  example/example.cpp
  python/CMakeLists.txt
  python/src/.gitignore
  python/src/etp/my_own_client_core_handlers.py
  python/src/etp/my_own_discovery_protocol_handlers.py
  python/src/etp/my_own_store_protocol_handlers.py
  python/src/etp_client_example.py
  python/src/example.py
  src/CMakeLists.txt
  src/common/EpcDocument.cpp
  src/common/EpcDocument.h
  src/epc/CoreProperty.cpp
  src/resqml2/AbstractIjkGridRepresentation.h
  src/resqml2/IjkGridParametricRepresentation.h
  src/resqml2_2/ContinuousColorMap.h
  src/resqml2_2/DiscreteColorMap.h
  swig/enumFixing.py
  swig/setup.py
  swig/swigEml2Include.i
  swig/swigEtp1_2Include.i
  swig/swigModule.i
  swig/swigProdml2_1Include.i
  swig/swigPythonGenerate.sh
  swig/swigResqml2Include.i
  swig/swigResqml2_0_1Include.i
  swig/swigResqml2_2Include.i
  swig/swigWitsml2_0Include.i
Labels: enhancement

#263 Streamlines support
  README.md
  cmake/swigCsInclude.i
  cmake/swigJavaInclude.i
  src/common/AbstractObject.cpp
  src/common/AbstractObject.h
  src/common/DataObjectRepository.cpp
  src/common/DataObjectRepository.h
  src/prodml2_1/FluidCharacterization.h
  src/resqml2/AbstractProperty.cpp
  src/resqml2/AbstractRepresentation.cpp
  src/resqml2/AbstractRepresentation.h
  src/resqml2/AbstractSurfaceFrameworkRepresentation.cpp
  src/resqml2/BlockedWellboreRepresentation.h
  src/resqml2/StreamlinesFeature.cpp
  src/resqml2/StreamlinesFeature.h
  src/resqml2/StreamlinesRepresentation.cpp
  src/resqml2/StreamlinesRepresentation.h
  src/resqml2_0_1/BlockedWellboreRepresentation.cpp
  src/resqml2_0_1/BlockedWellboreRepresentation.h
  src/resqml2_0_1/PointSetRepresentation.cpp
  src/resqml2_0_1/PolylineRepresentation.cpp
  src/resqml2_0_1/PolylineSetRepresentation.cpp
  src/resqml2_0_1/SealedSurfaceFrameworkRepresentation.cpp
  src/resqml2_0_1/StreamlinesFeature.cpp
  src/resqml2_0_1/StreamlinesFeature.h
  src/resqml2_0_1/StreamlinesRepresentation.cpp
  src/resqml2_0_1/StreamlinesRepresentation.h
  src/resqml2_0_1/TriangulatedSetRepresentation.cpp
  src/resqml2_2/BlockedWellboreRepresentation.cpp
  src/resqml2_2/BlockedWellboreRepresentation.h
  src/resqml2_2/PointSetRepresentation.cpp
  src/resqml2_2/PolylineRepresentation.cpp
  src/resqml2_2/PolylineSetRepresentation.cpp
  src/resqml2_2/SealedSurfaceFrameworkRepresentation.cpp
  src/resqml2_2/StreamlinesFeature.cpp
  src/resqml2_2/StreamlinesFeature.h
  src/resqml2_2/StreamlinesRepresentation.cpp
  src/resqml2_2/StreamlinesRepresentation.h
  src/resqml2_2/TriangulatedSetRepresentation.cpp
  swig/swigResqml2Include.i
  swig/swigResqml2_0_1Include.i
  swig/swigResqml2_2Include.i
  test/resqml2_test/Streamlines.cpp
  test/resqml2_test/Streamlines.h
  test/unitTest.cpp
Labels: enhancement

#264 More support for PRODML PVT
  example/example.cpp
  src/MacroDefinitions.h
  src/common/DataObjectRepository.cpp
  src/common/DataObjectRepository.h
  src/prodml2_1/FluidCharacterization.cpp
  src/prodml2_1/FluidCharacterization.h
  src/prodml2_1/FluidSystem.cpp
  src/prodml2_1/FluidSystem.h
  swig/swigProdml2_1Include.i
Labels: enhancement

#265 Fix Java wrappers and Linux ETP HDF proxy
  cmake/swigJavaInclude.i
  src/etp/EtpHdfProxy.cpp
Labels: bug

#267 Fix reading of IJK grids geometry by using hyperslabbing
  example/example.cpp
  src/resqml2/AbstractIjkGridRepresentation.cpp
  src/resqml2/AbstractIjkGridRepresentation.h
  src/resqml2/IjkGridExplicitRepresentation.cpp
  test/resqml2_test/FourSugarsParametricIjkGridWithGap.cpp
Labels: bug

#268 Bug fix : Setting min and max of floating point properties
  src/resqml2/AbstractValuesProperty.h
  src/resqml2/ContinuousProperty.cpp
  test/resqml2_test/ContinuousProperty.cpp
  test/resqml2_test/ContinuousProperty.h
  test/resqml2_test/ContinuousPropertyOnWellFrameTest.cpp
  test/unitTest.cpp
Labels: bug

#269 Prevent premature garbage collection of protocol handlers in C# and Java
  cmake/swigJavaInclude.i
  swig/swigEml2_3Include.i
  swig/swigEtp1_2Include.i
  swig/swigResqml2_2Include.i
Labels: bug

#270 Add unit test for wellbore trajectory in time
  test/resqml2_test/WellboreTrajectoryRepresentationTest.cpp
Labels: build

#272 Bug fix: ChannelMetaDataObject may lead to unresolved ref at link
  src/common/AbstractObject.h
  src/witsml2_0/ChannelMetaDataObject.h
  swig/swigWitsml2_0Include.i
Labels: bug

#271 Start to fix Java port and to integrate the port in CI
  .travis.yml
  README.md
  cmake/EtpClientExample.java
  cmake/EtpServerExample.java
  cmake/FesapiJavaExample.java
  cmake/MyOwnClientCoreHandlers.java
  cmake/MyOwnDiscoveryProtocolHandlers.java
  cmake/MyOwnServerCoreHandlers.java
  cmake/MyOwnStoreProtocolHandlers.java
  cmake/MyServerInitializationParameters.java
  cmake/swigJavaInclude.i
  cmake/swigWitsml2_0JavaInclude.i
  cs/CMakeLists.txt
  docker/trusty/Dockerfile
  example/example.cpp
  java/CMakeLists.txt
  java/src/com/f2i_consulting/example/.gitignore
  java/src/com/f2i_consulting/fesapi/.gitignore
  python/CMakeLists.txt
  src/resqml2/CategoricalProperty.cpp
  src/resqml2_0_1/CategoricalProperty.cpp
  src/resqml2_0_1/DiscreteProperty.cpp
  src/resqml2_0_1/PropertyKindMapper.cpp
  swig/swigModule.i
  swig/swigResqml2Include.i
Labels: build

#273 Honor Microsoft Namespace Naming Guidelines for C#
  README.md
  cmake/EtpClientExample.cs
  cmake/HdfProxyExample.cs
  cmake/HdfProxyFactoryExample.cs
  cmake/MyOwnClientCoreHandlers.cs
  cmake/MyOwnDiscoveryProtocolHandlers.cs
  cmake/MyOwnStoreProtocolHandlers.cs
  cmake/Program.cs
  cmake/cmake.PNG
  cmake/swigCsInclude.i
  cmake/swigWitsml2_0CsInclude.i
  cs/CMakeLists.txt
  docker/trusty/Dockerfile
  python/CMakeLists.txt
Labels: build
